spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password:
        url: jdbc:mysql://localhost:3306/comfohouse
        username: root
    jpa:
        database: mysql
        hibernate:
            ddl-auto: none
            dialect: org.hibernate.dialect.MySQLDialect
            database: mysql
            format_sql: true
            show_sql: true