spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: 1234
        url: jdbc:mysql://localhost:3306/comfohouse
        username: elice
    jpa:
        database: mysql
        hibernate:
            ddl-auto: create
            dialect: org.hibernate.dialect.MySQLDialect
            database: mysql
            format_sql: true
            show_sql: true