spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: Drugmaker124!
        url: jdbc:mysql://localhost:3306/order
        username: root
    jpa:
        hibernate:
            ddl-auto: create
